version: '2'

.catalog:
  name: word press
  version: v1.0.0
  description: |
    test app

services:
  wordpress:
    scale: 3
    start_on_create: true
  mysql:
    scale: 1
    start_on_create: true
  mywordpress:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: wordpress
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000

